server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: DOCTOR-SERVICE
          uri: lb://DOCTOR-SERVICE
          predicates:
            - Path=/doctor/**
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/department/**
eureka:
  client:
    fetch-registry:
      value: true
    register-with-eureka:
      value: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost